SELECT * FROM richlist.billionaires;
SELECT age  FROM richlist.billionaires;
SELECT source FROM richlist.billionaires;
SELECT industries FROM richlist.billionaires;
SELECT selfMade FROM richlist.billionaires;
SELECT birthDate FROM richlist.billionaires;
SELECT lastName FROM richlist.billionaires;
SELECT firstName FROM richlist.billionaires;
SELECT birthYear FROM richlist.billionaires;
